/**
 * Character Presets - 角色预设数据
 * 包含 129 个预设角色的图片和名称
 */

export interface CharacterPreset {
  name: string
  imageUrl: string
}

export const CHARACTER_PRESETS: CharacterPreset[] = [
  { name: 'Santa Claus', imageUrl: 'https://static.vidfab.ai/public/character/Santa-Claus.jpg' },
  { name: 'Reindee', imageUrl: 'https://static.vidfab.ai/public/character/Reindee.webp' },
  { name: 'Nutcracker', imageUrl: 'https://static.vidfab.ai/public/character/Nutcracker.webp' },
  { name: 'Grumpy', imageUrl: 'https://static.vidfab.ai/public/character/Grumpy.webp' },
  { name: 'Elf', imageUrl: 'https://static.vidfab.ai/public/character/Elf.webp' },
  { name: 'Santa', imageUrl: 'https://static.vidfab.ai/public/character/Santa.webp' },
  { name: 'Tung Tung Tung Sahur', imageUrl: 'https://static.vidfab.ai/public/character/Tung-Tung-Tung-Sahur.webp' },
  { name: 'Tralalero Tralala', imageUrl: 'https://static.vidfab.ai/public/character/Tralalero-Tralala.webp' },
  { name: 'Bombombini Gusini', imageUrl: 'https://static.vidfab.ai/public/character/Bombombini-Gusini.webp' },
  { name: 'Brr Brr Patapim', imageUrl: 'https://static.vidfab.ai/public/character/Brr-Brr-Patapim.webp' },
  { name: 'Trippi Troppi', imageUrl: 'https://static.vidfab.ai/public/character/Trippi-Troppi.webp' },
  { name: 'Lirili Larila', imageUrl: 'https://static.vidfab.ai/public/character/Lirili-Larila.webp' },
  { name: 'Chimpanzini Bananini', imageUrl: 'https://static.vidfab.ai/public/character/Chimpanzini-Bananini.webp' },
  { name: 'Bombardiro Crocodillo', imageUrl: 'https://static.vidfab.ai/public/character/Bombardiro-Crocodillo.webp' },
  { name: 'Ballerina Cappuccina', imageUrl: 'https://static.vidfab.ai/public/character/Ballerina-Cappuccina.webp' },
  { name: 'Cappuccino Assassino', imageUrl: 'https://static.vidfab.ai/public/character/Cappuccino-Assassino.webp' },
  { name: 'Elf Ranger Lana', imageUrl: 'https://static.vidfab.ai/public/character/Elf-Ranger-Lana.webp' },
  { name: 'Pikachu', imageUrl: 'https://static.vidfab.ai/public/character/Pikachu.webp' },
  { name: 'Pepe The Frog', imageUrl: 'https://static.vidfab.ai/public/character/Pepe-The-Frog.webp' },
  { name: 'Grogu', imageUrl: 'https://static.vidfab.ai/public/character/Grogu.webp' },
  { name: 'The Mandalorian', imageUrl: 'https://static.vidfab.ai/public/character/The-Mandalorian.webp' },
  { name: 'Minty', imageUrl: 'https://static.vidfab.ai/public/character/Minty.webp' },
  { name: 'Ganyu', imageUrl: 'https://static.vidfab.ai/public/character/Ganyu.webp' },
  { name: 'Paul Atreides', imageUrl: 'https://static.vidfab.ai/public/character/Paul-Atreides.webp' },
  { name: 'Doraemon', imageUrl: 'https://static.vidfab.ai/public/character/Doraemon.webp' },
  { name: 'Swole Doge', imageUrl: 'https://static.vidfab.ai/public/character/Swole-Doge.jpg' },
  { name: 'Ahsoka', imageUrl: 'https://static.vidfab.ai/public/character/Ahsoka.webp' },
  { name: 'Link', imageUrl: 'https://static.vidfab.ai/public/character/Link.webp' },
  { name: 'Darth Vader', imageUrl: 'https://static.vidfab.ai/public/character/Darth-Vader.webp' },
  { name: 'Moana', imageUrl: 'https://static.vidfab.ai/public/character/Moana.webp' },
  { name: 'Ty Lee', imageUrl: 'https://static.vidfab.ai/public/character/Ty-Lee.webp' },
  { name: 'Sasuke', imageUrl: 'https://static.vidfab.ai/public/character/Sasuke.webp' },
  { name: 'Jason Voorhees', imageUrl: 'https://static.vidfab.ai/public/character/Jason-Voorhees.webp' },
  { name: 'Tatsumaki', imageUrl: 'https://static.vidfab.ai/public/character/Tatsumaki.webp' },
  { name: 'Boba Fett', imageUrl: 'https://static.vidfab.ai/public/character/Boba-Fett.webp' },
  { name: 'Power Girl', imageUrl: 'https://static.vidfab.ai/public/character/Power-Girl.webp' },
  { name: 'Nightwing', imageUrl: 'https://static.vidfab.ai/public/character/Nightwing.webp' },
  { name: 'Mandalorian', imageUrl: 'https://static.vidfab.ai/public/character/Mandalorian.webp' },
  { name: 'Loki', imageUrl: 'https://static.vidfab.ai/public/character/Loki.webp' },
  { name: 'Deadpool', imageUrl: 'https://static.vidfab.ai/public/character/Deadpool.webp' },
  { name: 'Silver The Hedgehog', imageUrl: 'https://static.vidfab.ai/public/character/Silver-The-Hedgehog.webp' },
  { name: 'Predator', imageUrl: 'https://static.vidfab.ai/public/character/Predator.webp' },
  { name: 'Luffy', imageUrl: 'https://static.vidfab.ai/public/character/Luffy.webp' },
  { name: 'Elsa', imageUrl: 'https://static.vidfab.ai/public/character/Elsa.webp' },
  { name: 'Maki', imageUrl: 'https://static.vidfab.ai/public/character/Maki.webp' },
  { name: 'Michael Myers', imageUrl: 'https://static.vidfab.ai/public/character/Michael-Myers.webp' },
  { name: 'Goku Black', imageUrl: 'https://static.vidfab.ai/public/character/Goku-Black.webp' },
  { name: 'Judy Hopps', imageUrl: 'https://static.vidfab.ai/public/character/Judy-Hopps.webp' },
  { name: 'Gamera', imageUrl: 'https://static.vidfab.ai/public/character/Gamera.webp' },
  { name: 'Katara', imageUrl: 'https://static.vidfab.ai/public/character/Katara.webp' },
  { name: 'Scooby Doo', imageUrl: 'https://static.vidfab.ai/public/character/Scooby-Doo.webp' },
  { name: 'Sonic', imageUrl: 'https://static.vidfab.ai/public/character/Sonic.webp' },
  { name: 'Yoruichi', imageUrl: 'https://static.vidfab.ai/public/character/Yoruichi.webp' },
  { name: 'She Hulk', imageUrl: 'https://static.vidfab.ai/public/character/She-Hulk.webp' },
  { name: 'Lara Croft', imageUrl: 'https://static.vidfab.ai/public/character/Lara-Croft.webp' },
  { name: 'Angel', imageUrl: 'https://static.vidfab.ai/public/character/Angel.webp' },
  { name: 'Android 21', imageUrl: 'https://static.vidfab.ai/public/character/Android-21.webp' },
  { name: 'Rhysand', imageUrl: 'https://static.vidfab.ai/public/character/Rhysand.webp' },
  { name: 'Batman', imageUrl: 'https://static.vidfab.ai/public/character/Batman.webp' },
  { name: 'Kirby', imageUrl: 'https://static.vidfab.ai/public/character/Kirby.webp' },
  { name: 'Bayonetta', imageUrl: 'https://static.vidfab.ai/public/character/Bayonetta.webp' },
  { name: 'Poison Ivy', imageUrl: 'https://static.vidfab.ai/public/character/Poison-Ivy.webp' },
  { name: 'Black Widow', imageUrl: 'https://static.vidfab.ai/public/character/Black-Widow.webp' },
  { name: 'Sans', imageUrl: 'https://static.vidfab.ai/public/character/Sans.webp' },
  { name: 'Snape', imageUrl: 'https://static.vidfab.ai/public/character/Snape.webp' },
  { name: 'Hermione', imageUrl: 'https://static.vidfab.ai/public/character/Hermione.webp' },
  { name: 'Miles Morales', imageUrl: 'https://static.vidfab.ai/public/character/Miles-Morales.webp' },
  { name: 'Kakashi', imageUrl: 'https://static.vidfab.ai/public/character/Kakashi.webp' },
  { name: 'Wolverine', imageUrl: 'https://static.vidfab.ai/public/character/Wolverine.webp' },
  { name: 'Leo Valdez', imageUrl: 'https://static.vidfab.ai/public/character/Leo-Valdez.webp' },
  { name: 'Toji', imageUrl: 'https://static.vidfab.ai/public/character/Toji.webp' },
  { name: 'Goku', imageUrl: 'https://static.vidfab.ai/public/character/Goku.webp' },
  { name: 'Vaporeon', imageUrl: 'https://static.vidfab.ai/public/character/Vaporeon.webp' },
  { name: 'Annabeth Chase', imageUrl: 'https://static.vidfab.ai/public/character/Annabeth-Chase.webp' },
  { name: 'Pikachu 2', imageUrl: 'https://static.vidfab.ai/public/character/Pikachu-2.webp' },
  { name: 'Alastor', imageUrl: 'https://static.vidfab.ai/public/character/Alastor.webp' },
  { name: 'Vegeta', imageUrl: 'https://static.vidfab.ai/public/character/Vegeta.webp' },
  { name: 'Bowser', imageUrl: 'https://static.vidfab.ai/public/character/Bowser.webp' },
  { name: 'Spider Gwen', imageUrl: 'https://static.vidfab.ai/public/character/Spider-Gwen.webp' },
  { name: 'Deku', imageUrl: 'https://static.vidfab.ai/public/character/Deku.webp' },
  { name: 'Princess Peach', imageUrl: 'https://static.vidfab.ai/public/character/Princess-Peach.webp' },
  { name: 'Luce', imageUrl: 'https://static.vidfab.ai/public/character/Luce.webp' },
  { name: 'Gojo', imageUrl: 'https://static.vidfab.ai/public/character/Gojo.webp' },
  { name: 'Rias Gremory', imageUrl: 'https://static.vidfab.ai/public/character/Rias-Gremory.webp' },
  { name: 'Catwoman', imageUrl: 'https://static.vidfab.ai/public/character/Catwoman.webp' },
  { name: 'Lola Bunny', imageUrl: 'https://static.vidfab.ai/public/character/Lola-Bunny.webp' },
  { name: 'Inuyasha', imageUrl: 'https://static.vidfab.ai/public/character/Inuyasha.webp' },
  { name: 'Ahsoka Tano', imageUrl: 'https://static.vidfab.ai/public/character/Ahsoka-Tano.webp' },
  { name: 'Spiderman', imageUrl: 'https://static.vidfab.ai/public/character/Spiderman.webp' },
  { name: 'Harley Quinn', imageUrl: 'https://static.vidfab.ai/public/character/Harley-Quinn.webp' },
  { name: 'Venom', imageUrl: 'https://static.vidfab.ai/public/character/Venom.webp' },
  { name: 'Gwenpool', imageUrl: 'https://static.vidfab.ai/public/character/Gwenpool.webp' },
  { name: 'Jessica Rabbit', imageUrl: 'https://static.vidfab.ai/public/character/Jessica-Rabbit.webp' },
  { name: 'Joker', imageUrl: 'https://static.vidfab.ai/public/character/Joker.webp' },
  { name: 'Starfire', imageUrl: 'https://static.vidfab.ai/public/character/Starfire.webp' },
  { name: 'Uzi Doorman', imageUrl: 'https://static.vidfab.ai/public/character/Uzi-Doorman.webp' },
  { name: 'Draco', imageUrl: 'https://static.vidfab.ai/public/character/Draco.webp' },
  { name: 'Superman', imageUrl: 'https://static.vidfab.ai/public/character/Superman.webp' },
  { name: 'Gardevoir', imageUrl: 'https://static.vidfab.ai/public/character/Gardevoir.webp' },
  { name: 'Ariel', imageUrl: 'https://static.vidfab.ai/public/character/Ariel.webp' },
  { name: 'Aphmau', imageUrl: 'https://static.vidfab.ai/public/character/Aphmau.webp' },
  { name: 'Shadow The Hedgehog', imageUrl: 'https://static.vidfab.ai/public/character/Shadow-The-Hedgehog.webp' },
  { name: 'Godzilla', imageUrl: 'https://static.vidfab.ai/public/character/Godzilla.webp' },
  { name: 'Kefla', imageUrl: 'https://static.vidfab.ai/public/character/Kefla.webp' },
  { name: 'Nami', imageUrl: 'https://static.vidfab.ai/public/character/Nami.webp' },
  { name: 'Deadpool 2', imageUrl: 'https://static.vidfab.ai/public/character/Deadpool-2.webp' },
  { name: 'Angel Dust', imageUrl: 'https://static.vidfab.ai/public/character/Angel-Dust.webp' },
  { name: 'Gaston', imageUrl: 'https://static.vidfab.ai/public/character/Gaston.webp' },
  { name: 'Iron Man', imageUrl: 'https://static.vidfab.ai/public/character/Iron-Man.webp' },
  { name: 'Sukuna', imageUrl: 'https://static.vidfab.ai/public/character/Sukuna.webp' },
  { name: 'Naruto', imageUrl: 'https://static.vidfab.ai/public/character/Naruto.webp' },
  { name: 'Toy Chica', imageUrl: 'https://static.vidfab.ai/public/character/Toy-Chica.webp' },
  { name: 'Frieren', imageUrl: 'https://static.vidfab.ai/public/character/Frieren.webp' },
  { name: 'Steven Universe', imageUrl: 'https://static.vidfab.ai/public/character/Steven-Universe.webp' },
  { name: 'Super Mario', imageUrl: 'https://static.vidfab.ai/public/character/Super-Mario.webp' },
  { name: 'Percy Jackson', imageUrl: 'https://static.vidfab.ai/public/character/Percy-Jackson.webp' },
  { name: 'Samus', imageUrl: 'https://static.vidfab.ai/public/character/Samus.webp' },
  { name: 'Wonder Woman', imageUrl: 'https://static.vidfab.ai/public/character/Wonder-Woman.webp' },
  { name: 'Harry Potter', imageUrl: 'https://static.vidfab.ai/public/character/Harry-Potter.webp' },
  { name: 'Rosalina', imageUrl: 'https://static.vidfab.ai/public/character/Rosalina.webp' },
  { name: 'Chun Li', imageUrl: 'https://static.vidfab.ai/public/character/Chun-Li.webp' },
  { name: 'Spider-Man 2099', imageUrl: 'https://static.vidfab.ai/public/character/Spider-Man-2099.webp' },
  { name: 'Spongebob', imageUrl: 'https://static.vidfab.ai/public/character/Spongebob.webp' },
  { name: 'Hinata', imageUrl: 'https://static.vidfab.ai/public/character/Hinata.webp' },
  { name: 'Samus Aran', imageUrl: 'https://static.vidfab.ai/public/character/Samus-Aran.webp' },
  { name: 'Ginny Weasley', imageUrl: 'https://static.vidfab.ai/public/character/Ginny-Weasley.webp' },
  { name: 'Sailormoon', imageUrl: 'https://static.vidfab.ai/public/character/Sailormoon.webp' },
  { name: 'Beetlejuice', imageUrl: 'https://static.vidfab.ai/public/character/Beetlejuice.webp' },
  { name: 'Kratos', imageUrl: 'https://static.vidfab.ai/public/character/Kratos.webp' }
]

// 分组预设（可选）- 按类别分组方便筛选
export const CHARACTER_PRESET_CATEGORIES = {
  christmas: ['Santa Claus', 'Reindee', 'Nutcracker', 'Grumpy', 'Elf', 'Santa'],
  anime: ['Pikachu', 'Goku', 'Naruto', 'Luffy', 'Vegeta', 'Deku', 'Gojo'],
  marvel: ['Spiderman', 'Iron Man', 'Deadpool', 'Wolverine', 'Venom', 'Miles Morales'],
  starWars: ['Darth Vader', 'Ahsoka', 'The Mandalorian', 'Grogu', 'Boba Fett'],
  // ... 可以继续添加更多分类
}
