/**
 * Video Agent Beta - AI 灵感脚本选择弹框
 * 显示 5 个 AI 生成的脚本创意供用户选择
 */

'use client'

import { useState } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Sparkles, Clock, Tag } from 'lucide-react'

interface ScriptInspiration {
  title: string
  description: string
  script: string
  style: string
  duration: number
  hashtags: string[]
}

interface InspirationDialogProps {
  isOpen: boolean
  onClose: () => void
  inspirations: ScriptInspiration[]
  onSelect: (script: string, style: string, duration: number) => void
}

const STYLE_LABELS: Record<string, string> = {
  auto: 'Auto',
  comedy: 'Comedy',
  mystery: 'Mystery',
  moral: 'Moral',
  twist: 'Twist',
  suspense: 'Suspense',
  warmth: 'Warmth',
  inspiration: 'Inspiration'
}

export default function InspirationDialog({
  isOpen,
  onClose,
  inspirations,
  onSelect
}: InspirationDialogProps) {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null)

  const handleSelect = () => {
    if (selectedIndex === null) return

    const selected = inspirations[selectedIndex]
    onSelect(selected.script, selected.style, selected.duration)
    onClose()
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-2xl">
            <Sparkles className="w-6 h-6 text-primary" />
            AI Script Inspirations
          </DialogTitle>
          <DialogDescription>
            Choose from 5 trending video script ideas generated by AI. Click to select and auto-fill.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 mt-4">
          {inspirations.map((inspiration, index) => (
            <Card
              key={index}
              className={`
                cursor-pointer transition-all
                ${selectedIndex === index
                  ? 'border-primary border-2 shadow-lg'
                  : 'border-border hover:border-primary/50'
                }
              `}
              onClick={() => setSelectedIndex(index)}
            >
              <CardContent className="pt-6">
                {/* 标题 */}
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-lg font-semibold">
                    {index + 1}. {inspiration.title}
                  </h3>
                  <Badge variant="outline" className="ml-2">
                    {STYLE_LABELS[inspiration.style] || inspiration.style}
                  </Badge>
                </div>

                {/* 描述 */}
                <p className="text-sm text-muted-foreground mb-3">
                  {inspiration.description}
                </p>

                {/* 脚本预览 */}
                <div className="bg-muted/50 rounded-lg p-3 mb-3">
                  <p className="text-xs text-foreground/80 line-clamp-3">
                    {inspiration.script}
                  </p>
                </div>

                {/* 元数据 */}
                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                  {/* 时长 */}
                  <div className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    <span>{inspiration.duration}s</span>
                  </div>

                  {/* 话题标签 */}
                  <div className="flex items-center gap-1 flex-1">
                    <Tag className="w-3 h-3" />
                    <span className="truncate">
                      {inspiration.hashtags.slice(0, 3).join(' ')}
                    </span>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* 操作按钮 */}
        <div className="flex gap-3 mt-6">
          <Button
            variant="outline"
            onClick={onClose}
            className="flex-1"
          >
            Cancel
          </Button>
          <Button
            onClick={handleSelect}
            disabled={selectedIndex === null}
            className="flex-1"
          >
            Use Selected Script
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
